name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: jal
          POSTGRES_USER: jal
          POSTGRES_PASSWORD: jal
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: jal
          POSTGRES_USER: jal
          POSTGRES_PASSWORD: jal
          SECRET_KEY: test-secret
          ADMIN_EMAIL: admin@example.com
          ADMIN_PASSWORD: admin
        run: pytest -q
